stages:
  check_packages:
    cmd: python src/stages/check_pkgs.py --config=params.yaml
    always_changed: true
    outs:
      - pkg_list.txt
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
      - src/stages/data_load.py
      - pkg_list.txt
    params:
      - base
      - data_load
    outs:
      - ${data_load.data_dir}/${data_load.new_dirname}/images
      - ${data_load.data_dir}/${data_load.new_dirname}/masks
  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
      - src/stages/data_split.py
      - pkg_list.txt
      - ${data_load.data_dir}/${data_load.new_dirname}/images
      - ${data_load.data_dir}/${data_load.new_dirname}/masks
    params:
      - base
      - data_load
      - data_split
    outs:
      - ${data_split.train_img_dir_path}
      - ${data_split.train_mask_dir_path}
      - ${data_split.test_img_dir_path}
      - ${data_split.test_mask_dir_path}
  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
      - ${data_split.train_img_dir_path}
      - ${data_split.train_mask_dir_path}
      - src/stages/train.py
      - pkg_list.txt
    params:
      - base
      - data_split
      - train
  evaluate:
    cmd: python src/stages/eval.py --config=params.yaml
    deps:
      - ${data_split.test_img_dir_path}
      - ${data_split.test_mask_dir_path}
      - models/model_pickle_fastai.pkl
      - src/stages/eval.py
      - pkg_list.txt
    params:
      - base
      - train
      - data_split
      - evaluate
    metrics:
      - reports/metrics.json:
          cache: False
