stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
      - src/stages/data_load.py
    params:
      - base
      - data_load
    outs:
      - ${data_load.data_dir}/${data_load.new_dirname}/images
      - ${data_load.data_dir}/${data_load.new_dirname}/masks
  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
      - src/stages/data_split.py
      - ${data_load.data_dir}/${data_load.new_dirname}/images
      - ${data_load.data_dir}/${data_load.new_dirname}/masks
    params:
      - base
      - data_load
      - data_split
    outs:
      - ${data_split.train_img_dir_path}
      - ${data_split.train_mask_dir_path}
      - ${data_split.test_img_dir_path}
      - ${data_split.test_mask_dir_path}
  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
      - ${data_split.train_img_dir_path}
      - ${data_split.train_mask_dir_path}
      - src/stages/train.py
    params:
      - base
      - data_split
      - train
    outs:
      - ${train.model_pickle_dir_path}
    plots:
      - training_metrics/scalars:
          cache: false
  evaluate:
    cmd: python src/stages/eval.py --config=params.yaml
    deps:
      - ${train.model_pickle_dir_path}
      - ${data_split.test_img_dir_path}
      - ${data_split.test_mask_dir_path}
      - src/stages/eval.py
    params:
      - base
      - train
      - data_split
      - evaluate
    outs:
      - ${data_load.data_dir}/test_preds
    metrics:
      - metrics.json:
          cache: false
