base:
  project: defect_detection
  pkg_list_fname: pkg_list.txt
  random_state: 0

data_load:
  dataset_url: https://github.com/abin24/Magnetic-tile-defect-datasets./archive/refs/heads/master.zip
  data_dir: data
  orig_dirname: Magnetic-tile-defect-datasets.-master
  new_dirname: MAGNETIC_TILE_SURFACE_DEFECTS

data_split:
  test_pct: 0.2
  train_img_dir_path: data/MAGNETIC_TILE_SURFACE_DEFECTS/train_images
  train_mask_dir_path: data/MAGNETIC_TILE_SURFACE_DEFECTS/train_masks
  test_img_dir_path: data/MAGNETIC_TILE_SURFACE_DEFECTS/test_images
  test_mask_dir_path: data/MAGNETIC_TILE_SURFACE_DEFECTS/test_masks

train:
  img_size: 200
  valid_pct: 0.2
  learning_rate: 0.001
  batch_size: 16
  n_epochs: 10
  use_cpu: false
  model_pickle_dir_path: models
  model_pickle_fname: model_pickle_fastai.pkl

evaluate:
  save_test_preds: true
  metrics_file: metrics.json
