on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
          pip install pipenv && echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - run: |
          pipenv install --skip-lock
          echo "Run pip freeze"
          pipenv run pip freeze
          echo "Run dvc doctor"
          pipenv run dvc doctor