name: train-my-model

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-east-1 \
          --cloud-type g3s.xlarge \
          --cloud-hdd-size 64 \
          --labels=cml-runner

  run:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container:
      image: docker://iterativeai/cml
      options: --gpus all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install pipenv
        run: pip install pipenv
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}:${PYTHONPATH}" >> $GITHUB_ENV
      - name: cml
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pipenv install --dev
          pipenv run dvc repro
          pipenv run dvc push

          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          echo "## A few random test images" >> report.md
          cml-publish data/test_preds/$(ls data/test_preds/ | shuf -n 1) --md >> report.md
          cml-publish data/test_preds/$(ls data/test_preds/ | shuf -n 1) --md >> report.md
          cml-publish data/test_preds/$(ls data/test_preds/ | shuf -n 1) --md >> report.md
          cml-publish data/test_preds/$(ls data/test_preds/ | shuf -n 1) --md >> report.md
          cml-send-comment report.md
