name: train-model

on:
  push:
    branches-ignore: # exclude master and dev below
      - master
      - dev

jobs:
  deploy-runner:
    if: contains(github.event.head_commit.message, '[cml]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # set your own via gh cli or UI
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # set your own via gh cli or UI
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # set your own via gh cli or UI
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # set your own via gh cli or UI
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-east-1 \
          --cloud-type g4dn.xlarge \
          --labels=cml-runner
  train-model:
    if: contains(github.event.head_commit.message, '[cml]')
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container:
      image: docker://iterativeai/cml
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup Git User
        run: |
          # Get user name and email from previous commit
          USER_NAME=$(git --no-pager log --format=format:'%ae' -n 1)
          USER_EMAIL=$(git --no-pager log --format=format:'%ae' -n 1)
          git config --local user.name "$USER_NAME"
          git config --local user.email "$USER_EMAIL"
      - name: Install pipenv
        run: pip install pipenv
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - name: dvc-repro-cml
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # set your own via gh cli or UI
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # set your own via gh cli or UI
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # set your own via gh cli or UI
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # set your own via gh cli or UI
        run: |
          # Install dependencies
          pipenv install --skip-lock

          # Run dvc pipeline
          pipenv run dvc pull
          pipenv run dvc repro

          # Save original commit message
          COMMIT_MESSAGE=$(git log -1 --format=%s)

          # Add files to git and push
          git reset --soft HEAD~2
          git add metrics.json training_metrics.json training_metrics training_metrics_dvc_plots/index.html
          git commit -m "$COMMIT_MESSAGE [skip ci]"
          git push

          # Create CML report
          echo "## Metrics" >> report.md
          dvc metrics show --md >> report.md
          echo "## A few random test images" >> report.md
          for file in $(ls data/test_preds/ |sort -R |tail -20); do cml-publish data/test_preds/$file --md >>report.md; done
          cml send-comment --update report.md
